# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  tp_config = debug
endif
ifeq ($(config),release)
  tp_config = release
endif

PROJECTS := tp

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

tp:
ifneq (,$(tp_config))
	@echo "==== Building tp ($(tp_config)) ===="
	@${MAKE} --no-print-directory -C . -f tp.make config=$(tp_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f tp.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   tp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"